name: adder-ts

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout to repository
        uses: actions/checkout@v2
      - name: install and deploy
        run: npm ci
      - name: publish to registry
        uses: actions/setup-node@v2
        with:
          node-version: 20
          registery-url: 'https://npm.pkg.github.com'
          scope: '@rezash798'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
